#ifndef _TOOLBOX_LDS_ATTRIBUTE_IDS_
#define _TOOLBOX_LDS_ATTRIBUTE_IDS_


// Server attributes for color control
#define ZCL_COLOR_CONTROL_CURRENT_HUE_ATTRIBUTE_ID 0x0000                      // Ver.: always
#define ZCL_COLOR_CONTROL_CURRENT_SATURATION_ATTRIBUTE_ID 0x0001               // Ver.: always
#define ZCL_COLOR_CONTROL_REMAINING_TIME_ATTRIBUTE_ID 0x0002                   // Ver.: always
#define ZCL_COLOR_CONTROL_CURRENT_X_ATTRIBUTE_ID 0x0003                        // Ver.: always
#define ZCL_COLOR_CONTROL_CURRENT_Y_ATTRIBUTE_ID 0x0004                        // Ver.: always
#define ZCL_COLOR_CONTROL_DRIFT_COMPENSATION_ATTRIBUTE_ID 0x0005               // Ver.: always
#define ZCL_COLOR_CONTROL_COMPENSATION_TEXT_ATTRIBUTE_ID 0x0006                // Ver.: always
#define ZCL_COLOR_CONTROL_COLOR_TEMPERATURE_ATTRIBUTE_ID 0x0007                // Ver.: always
#define ZCL_COLOR_CONTROL_COLOR_MODE_ATTRIBUTE_ID 0x0008                       // Ver.: always
#define ZCL_COLOR_CONTROL_CURRENT_X_AND_Y_ATTRIBUTE_ID  0x000A                 // Ver.: always
#define ZCL_COLOR_CONTROL_OPTIONS_ATTRIBUTE_ID 0x000F                          // Ver.: since zcl-6.0-15-02017-001
#define ZCL_COLOR_CONTROL_ENHANCED_CURRENT_HUE_ATTRIBUTE_ID 0x4000             // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_ENHANCED_COLOR_MODE_ATTRIBUTE_ID 0x4001              // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_LOOP_ACTIVE_ATTRIBUTE_ID 0x4002                // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_LOOP_DIRECTION_ATTRIBUTE_ID 0x4003             // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_LOOP_TIME_ATTRIBUTE_ID 0x4004                  // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_LOOP_START_ENHANCED_HUE_ATTRIBUTE_ID 0x4005    // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_LOOP_STORED_ENHANCED_HUE_ATTRIBUTE_ID 0x4006   // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_CAPABILITIES_ATTRIBUTE_ID 0x400A               // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_TEMP_PHYSICAL_MIN_ATTRIBUTE_ID 0x400B          // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_COLOR_TEMP_PHYSICAL_MAX_ATTRIBUTE_ID 0x400C          // Ver.: since zll-1.0-11-0037-10
#define ZCL_COLOR_CONTROL_TEMPERATURE_LEVEL_MIN_MIREDS_ATTRIBUTE_ID 0x400D     // Ver.: since l&o-1.0-15-0014-04
#define ZCL_START_UP_COLOR_TEMPERATURE_MIREDS_ATTRIBUTE_ID 0x4010              // Ver.: since l&o-1.0-15-0014-04

// Server attributes for cluster: Level Control
#define ZCL_CURRENT_LEVEL_ATTRIBUTE_ID (0x0u)
#define ZCL_LEVEL_CONTROL_REMAINING_TIME_ATTRIBUTE_ID (0x1u)
#define ZCL_OPTIONS_ATTRIBUTE_ID (0xFu)
#define ZCL_ON_OFF_TRANSITION_TIME_ATTRIBUTE_ID (0x10u)
#define ZCL_ON_LEVEL_ATTRIBUTE_ID (0x11u)
#define ZCL_ON_TRANSITION_TIME_ATTRIBUTE_ID (0x12u)
#define ZCL_OFF_TRANSITION_TIME_ATTRIBUTE_ID (0x13u)
#define ZCL_DEFAULT_MOVE_RATE_ATTRIBUTE_ID (0x14u)
#define ZCL_START_UP_CURRENT_LEVEL_ATTRIBUTE_ID (0x4000u)


// Server attributes for cluster: On/off
#define ZCL_ON_OFF_ATTRIBUTE_ID (0x0u)
#define ZCL_GLOBAL_SCENE_CONTROL_ATTRIBUTE_ID (0x4000u)
#define ZCL_ON_TIME_ATTRIBUTE_ID (0x4001u)
#define ZCL_OFF_WAIT_TIME_ATTRIBUTE_ID (0x4002u)
#define ZCL_START_UP_ON_OFF_ATTRIBUTE_ID (0x4003u)

#endif