#ifndef _TOOLBOX_LDS_ERROR_CODES_
#define _TOOLBOX_LDS_ERROR_CODES_

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  LDS_SUCCESS = 0,
  LDS_STATUS_VALUE_NOT_FOUND,
  LDS_STATUS_ABORT,
  LDS_ERROR_BAD_ARGUMENT,
  LDS_ERROR_OPERATION_IN_PROGRESS,
  LDS_ERROR_OUT_OF_MEMORY,
  LDS_ERROR_INVALID_PARAMETER,
  LDS_ERROR_NOT_INITIALIZED,
  LDS_ERROR_UNSUPPORTED_ATTRIBUTE,
  LDS_ERROR_INVALID_DATA_TYPE,
  LDS_ERROR_READ_ONLY,
  LDS_ERROR_NOT_IMPLEMENTED,
  LDS_ERROR_UNKNOWN
} lds_status_t;

#ifdef __cplusplus
}
#endif

#endif // _TOOLBOX_LDS_ERROR_CODES_